### PR TITLE
chore(contributors): add @ryandrewjohnson for his blogpost

### PR DESCRIPTION
**Pull request by kentcdodds**
[link](https://medium.com/@ryandrewjohnson/one-webpack-config-to-rule-them-all-environments-that-is-277457769779)

Is that alright @ryandrewjohnson?

### CODE REVIEW

**Comment by ryandrewjohnson** [comment]
@kentcdodds can you just swap any references to http://shakainteractive.com and point straight to my github profile? I can make change later tonight if that's easier -- let me know.

**Comment by kentcdodds** [comment]
Done @ryandrewjohnson!

**Comment by kentcdodds** [comment]
Thanks again @ryandrewjohnson!

**Comment by kentcdodds** [comment]
You know what, we should add a section with a link to your blogpost. Wanna do that? Make sure to update your contributions array to include "docs" :)

**Pull request merged**
